syntax = "proto3";

package prover.v1;

import "include/v1/includes.proto";

// timestamps are represented in unix time in seconds

enum ResultCode {
  OK = 0;
  INVALID_PARAMETER = 1;
  INTERNAL_ERROR = 2;
  BUSY = 3;
  UNSPECIFIED = 4;
}

message Result {
  ResultCode code = 1;
  string message = 2;
}

service ProverService {
  rpc SplitElf(SplitElfRequest) returns (SplitElfResponse) {}
  rpc Prove(ProveRequest) returns (ProveResponse) {}
  rpc Aggregate(AggregateRequest) returns (AggregateResponse) {}
  rpc SnarkProof(SnarkProofRequest) returns (SnarkProofResponse) {}
  rpc SingleNode(SingleNodeRequest) returns (SingleNodeResponse) {}
}

message SplitElfRequest {
  string proof_id = 1;
  string computed_request_id = 2;
  string base_dir = 3;
  string elf_path = 4;
  string seg_path = 5;
  uint32 seg_size = 7;
  string private_input_path = 10;
  string receipt_inputs_path = 12;
  string program_id = 13;
}

message SplitElfResponse {
  string proof_id = 1;
  string computed_request_id = 2;
  Result result = 3;
  uint64 total_steps = 4;
  uint32 total_segments = 5;
}

message ProveRequest {
  string proof_id = 1;
  string computed_request_id = 2;
  string program_id = 3;
  string segment = 4;
  uint32 seg_size = 6;
  string elf_path = 7;
  uint32 index = 9;
}

message ProveResponse {
  string proof_id = 1;
  string computed_request_id = 2;
  bytes output_receipt = 3;
  Result result = 4;
}

message AggregateRequest {
  string proof_id = 1;
  string computed_request_id = 2;
  bytes vk = 7;
  repeated includes.v1.AggregateInput inputs = 8;
  bool is_final = 9;
  bool is_first_shard = 10;
  bool is_leaf_layer = 11;
  bool is_deferred = 12;
}

message AggregateResponse {
  string proof_id = 1;
  string computed_request_id = 2;
  bytes agg_receipt = 3;
  Result result = 4;
}

message SnarkProofRequest {
  string proof_id = 1;
  string computed_request_id = 2;
  bytes agg_receipt = 4;
  bool from_input = 5; // if true, the agg_receipt is from input, otherwise it is from agg output
}

message SnarkProofResponse {
  string proof_id = 1;
  string computed_request_id = 2;
  bytes snark_proof_with_public_inputs = 3;
  Result result = 4;
}

message SingleNodeRequest {
  string proof_id = 1;
  string computed_request_id = 2;
  string base_dir = 3;
  string elf_path = 4;
  string private_input_path = 5;
  string receipt_inputs_path = 6;
  string program_id = 7;
  includes.v1.Step target_step = 8;
  uint32 seg_size = 9;
}

message SingleNodeResponse {
  string proof_id = 1;
  string computed_request_id = 2;
  bytes output = 3;
  uint64 total_steps = 4;
  Result result = 5;}
